development:
  adapter: postgresql
  database: apiaweberdev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: apiawebertest
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: apiaweberprod
  pool: 5
  timeout: 5000